dist: bionic
language: Rust

rust:
- stable
- beta
- nightly

cache:
  directories:
  - "$TRAVIS_BUILD_DIR/target"

env:
  global:
  - PATH="$HOME/.cargo/bin:$PATH"

install:
- ci/travis/install.sh

script:
- cargo tarpaulin -v --out Xml --ciserver travis-ci

after_script:
- curl -SsL "https://codecov.io/bash" | bash -s - -y ci/codecov.yml

before_cache:
- cargo cache -a

deploy:
  - provider: cargo
    on:
      rust: stable
      tags: true
  - provider: script
    script: ci/travis/deploy.sh
    on:
      rust: stable
      tags: true

notifications:
  email:
  - althonosdev@gmail.com
